Add support queue system while sending messages
mohammad-fouladgar/laravel-mobile-verification pull request #166
Opened 2021-04-04 20:16 UTC by sepisoltani

Thanks @mohammad-fouladgar  for the great package 
This PR is belongs to #24

2021-04-06 11:12 UTC, 50bhan commented
@sepisoltani Thank you for your PR. Although I have a comment here. 

I think here we can queue the listener instead of the notification. Because it's really easier and more maintainable for the future. We only need to add another listener (Queueable Listener) and in the service provider, we'll conditionally bind one of the listeners to the `event` (based on the config).

2021-04-06 12:39 UTC, mohammad-fouladgar commented
@50bhan Thanks for your point. 
Of course, we should do it. Because after running queue, the listener will be executed and makes a token at the correct expires time. But if we use the queue in the notification, the listener makes a token, and then the notification will be queued which is not safe.

2021-04-06 13:49 UTC, sepisoltani commented
This new approach does not work in laravel 6 and 7 :(
Im gonna change it.

2021-04-06 14:02 UTC, 50bhan commented
@sepisoltani You can just add another listener and implement it from `ShouldQueue` interface. Then bind one of the listeners to the `event` based on config. This approach will work on L6, L7 and L8.

2021-04-06 15:23 UTC, sepisoltani commented
@50bhan thanks Sobhan . take a look

2021-04-06 15:58 UTC, 50bhan requested changes

2021-04-06 15:58 UTC, 50bhan commented on src/EventServiceProvider.php
> +        if (config('mobile_verifier.queue.connection') == 'sync') {
Please you strict comparison `===`

2021-04-06 15:58 UTC, 50bhan commented on src/EventServiceProvider.php
> +            Event::listen(Registered::class, [SendMobileVerificationNotification::class, 'handle']);
I believe we can have this here -> Event::listen(Registered::class, SendMobileVerificationNotification::class);

2021-04-06 15:58 UTC, 50bhan commented on src/Listeners/AbstractMobileVerificationListener.php
> +
Please remove this empty line (To prevent the CI failure)

2021-04-06 15:58 UTC, 50bhan commented on src/Listeners/SendMobileVerificationNotificationQueueable.php
> +
Please remove this empty line (To prevent the CI failure)

2021-04-06 15:58 UTC, 50bhan commented on src/Listeners/SendMobileVerificationNotificationQueueable.php
> +
Please remove this empty line (To prevent the CI failure)

2021-04-06 15:58 UTC, 50bhan commented on src/Listeners/SendMobileVerificationNotificationQueueable.php
> +    public $connection = null;
Null assignment can be safely removed.

2021-04-06 15:58 UTC, 50bhan commented on src/Listeners/SendMobileVerificationNotificationQueueable.php
> +    public $queue = null;
Null assignment can be safely removed.

2021-04-06 16:00 UTC, 50bhan commented
@sepisoltani Thank you for the new implementation. I left some comments, and I'll be grateful if you can add a test case for these changes in `ListenerTest` class.

2021-04-07 07:34 UTC, mohammad-fouladgar commented
@sepisoltani I got it 😃  As I told you, the default Dispatcher is building the event listeners without calling the constructor and then directly access the `$queue` attribute without the getter method.(also $connection attrib.)
So we can write a magic method getter for the queueable listener like this:
```php

    public function __get($name)
    {
        switch ($name) {
            case 'tries':
                return config('mobile_verifier.queue.tries');
                break;
            case 'timeout':
                return config('mobile_verifier.queue.timeout');
                break;
            case 'connection':
                return config('mobile_verifier.queue.connection');
                break;
            case 'queue':
                return config('mobile_verifier.queue.queue');
                break;
        }
    }
```

2021-04-07 12:36 UTC, sepisoltani commented
@50bhan @mohammad-fouladgar Thanks . it will be done soon

2021-04-07 19:32 UTC, mohammad-fouladgar commented
@sepisoltani For having an assertion test for listening we have to add a method like this for supporting Laravel < v8.


```php
 use Illuminate\Contracts\Events\Dispatcher;
 use ReflectionFunction;

 private function assertListening($expectedEvent, $expectedListener)
    {
        $dispatcher = $this->app->make(Dispatcher::class);

        foreach ($dispatcher->getListeners($expectedEvent) as $listenerClosure) {

            $actualListener = (new ReflectionFunction($listenerClosure))
                ->getStaticVariables()['listener'];

            if ($actualListener === $expectedListener ||
                ($actualListener instanceof Closure &&
                    $expectedListener === Closure::class)) {
                $this->assertTrue(true);

                return;
            }
        }

        $this->assertTrue(
            false,
            sprintf(
                'Event [%s] does not have the [%s] listener attached to it',
                $expectedEvent,
                print_r($expectedListener, true)
            )
        );
    }
   ```

2021-04-08 09:24 UTC, mohammad-fouladgar commented
@sepisoltani For having an assertion test for listening we have to add a method in the `TestCase.php` file like this for supporting Laravel < v8.
```php
protected function assertListening($expectedEvent, $expectedListener)
    {
        $dispatcher = $this->app->make(Dispatcher::class);

        foreach ($dispatcher->getListeners($expectedEvent) as $listenerClosure) {
            $actualListener = (new ReflectionFunction($listenerClosure))
                ->getStaticVariables()['listener'];

            if ($actualListener === $expectedListener ||
                ($actualListener instanceof Closure &&
                    $expectedListener === Closure::class)) {
                $this->assertTrue(true);

                return;
            }
        }

        $this->assertTrue(
            false,
            sprintf(
                'Event [%s] does not have the [%s] listener attached to it',
                $expectedEvent,
                print_r($expectedListener, true)
            )
        );
    }
```

2021-04-08 09:36 UTC, mohammad-fouladgar commented
@sepisoltani When you are testing if you change the config for example `config()->set('mobile_verifier.queue.connection');` this will not be changed in the service provider. So you have to change the environment config through override this method in your test: 
```php
protected function getEnvironmentSetUp($app): void
{
    parent::getEnvironmentSetUp($app);
    $app['config']->set('mobile_verifier.queue.connection', 'database');
}
```

2021-04-08 11:16 UTC, sepisoltani commented
@mohammad-fouladgar Thanks for your help . Please check

2021-04-08 11:33 UTC, mohammad-fouladgar commented
@sepisoltani It was a good challenge for us :). Welcome to our community. 🎉 

I'll merge this PR as soon as possible.

2021-04-08 12:01 UTC, 50bhan approved these changes

2021-04-08 12:02 UTC, merged

2021-04-08 15:36 UTC, sepisoltani commented
@mohammad-fouladgar @50bhan I appreciate that . Thanks